services:

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ./url_data:/data/db

    ports:
      - "27018:27017"
    networks:
      - url-net

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    healthcheck:
      test: ["CMD", "mongosh", "--host", "localhost", "--username", "${MONGO_INITDB_ROOT_USERNAME}", "--password", "${MONGO_INITDB_ROOT_PASSWORD}", "--authenticationDatabase", "admin", "--eval", "db.runCommand({ ping: 2 }).ok"]

      interval: 11s
      retries: 6
      start_period: 61s
      timeout: 6s

  backend:
    build:
      context: ./backend/
    container_name: backend
    
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      NODE_ENV: development
      MONGO_URL_DEV: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/mydb?authSource=admin
      APP_URL: http://localhost:3000/
      JWT_SECRET: anduila
    networks:
      - url-net
    ports:
      - "3000:3000"
    
    depends_on:
      mongo:
        condition: service_healthy

    restart: always

  frontend:
    build:
      context: ./frontend/
    container_name: frontend
    networks:
      - url-net
    environment:
      VITE_API_BASE_URL: http://localhost:3000
    ports:
      - "5000:80"

    restart: always

volumes:
  url_data:

networks:
  url-net:
